version: '3.9'

services:

  frontend:
    build:
      context: ./FRONT-STAGE2
      dockerfile: Dockerfile
    ports:
      - 9000:3000
    depends_on:
      - backend

  backend:
    build:
      context: ./BACK-STAGE2
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - server.port=8080
      - springdoc.api-docs.path=/documentation
      - credentials.path=app/credentials.json
      - spring.datasource.url=jdbc:postgresql://postgres:5432/postgres
      - spring.datasource.username=user
      - spring.datasource.password=jacobo0312
      - spring.datasource.driver-class-name=org.postgresql.Driver
      - spring.jpa.hibernate.ddl-auto=update
    depends_on:
      - postgres

  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=jacobo0312
      - POSTGRES_USER=user
      - POSTGRES_DB=postgres
